# Generated by Django 5.1.6 on 2025-04-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
                ('min_experience', models.IntegerField()),
                ('company_name', models.CharField(max_length=40)),
                ('requirements', models.TextField(max_length=250)),
            ],
        ),
    ]
