# Generated by Django 5.1.6 on 2025-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_model',
            name='min_experience',
            field=models.CharField(max_length=35),
        ),
    ]
