# Generated by Django 5.1.6 on 2025-04-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_create_model_min_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='looking_for_offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=200)),
                ('abilites', models.CharField(max_length=200)),
            ],
        ),
    ]
