# Generated by Django 5.1.6 on 2025-04-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_looking_for_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='looking_for_offers',
            old_name='abilites',
            new_name='abilities',
        ),
    ]
